nmHoistingLimits: workspaces
nmMode: hardlinks-local
nodeLinker: node-modules
enableScripts: false

npmAuthToken: "${NPM_AUTH_TOKEN-undefined}"

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-3.8.1.cjs
